# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/Entertaiment/Programy/VHDL/VHDL/LooperV2/LooperV2.srcs/sources_1/ip/div_gen_0_1/div_gen_0.xci
# IP: The module: 'div_gen_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Entertaiment/Programy/VHDL/VHDL/LooperV2/LooperV2.gen/sources_1/ip/div_gen_0/div_gen_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'div_gen_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: d:/Entertaiment/Programy/VHDL/VHDL/LooperV2/LooperV2.srcs/sources_1/ip/div_gen_0_1/div_gen_0.xci
# IP: The module: 'div_gen_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Entertaiment/Programy/VHDL/VHDL/LooperV2/LooperV2.gen/sources_1/ip/div_gen_0/div_gen_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'div_gen_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
