# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/VHDL/Nexys-Video-Master.xdc

# Block Designs: bd/dfx_controller_setup/dfx_controller_setup.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==dfx_controller_setup || ORIG_REF_NAME==dfx_controller_setup} -quiet] -quiet

# IP: bd/dfx_controller_setup/ip/dfx_controller_setup_dfx_controller_0_0/dfx_controller_setup_dfx_controller_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==dfx_controller_setup_dfx_controller_0_0 || ORIG_REF_NAME==dfx_controller_setup_dfx_controller_0_0} -quiet] -quiet

# IP: bd/dfx_controller_setup/ip/dfx_controller_setup_blk_mem_gen_0_0/dfx_controller_setup_blk_mem_gen_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==dfx_controller_setup_blk_mem_gen_0_0 || ORIG_REF_NAME==dfx_controller_setup_blk_mem_gen_0_0} -quiet] -quiet

# IP: bd/dfx_controller_setup/ip/dfx_controller_setup_axi_bram_ctrl_0_0/dfx_controller_setup_axi_bram_ctrl_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==dfx_controller_setup_axi_bram_ctrl_0_0 || ORIG_REF_NAME==dfx_controller_setup_axi_bram_ctrl_0_0} -quiet] -quiet

# IP: bd/dfx_controller_setup/ip/dfx_controller_setup_rst_sys_clock_50M_0/dfx_controller_setup_rst_sys_clock_50M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==dfx_controller_setup_rst_sys_clock_50M_0 || ORIG_REF_NAME==dfx_controller_setup_rst_sys_clock_50M_0} -quiet] -quiet

# IP: bd/dfx_controller_setup/ip/dfx_controller_setup_axi_interconnect_0_0/dfx_controller_setup_axi_interconnect_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==dfx_controller_setup_axi_interconnect_0_0 || ORIG_REF_NAME==dfx_controller_setup_axi_interconnect_0_0} -quiet] -quiet

# IP: bd/dfx_controller_setup/ip/dfx_controller_setup_ila_0_1/dfx_controller_setup_ila_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==dfx_controller_setup_ila_0_1 || ORIG_REF_NAME==dfx_controller_setup_ila_0_1} -quiet] -quiet

# IP: bd/dfx_controller_setup/ip/dfx_controller_setup_ila_1_0/dfx_controller_setup_ila_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==dfx_controller_setup_ila_1_0 || ORIG_REF_NAME==dfx_controller_setup_ila_1_0} -quiet] -quiet

# IP: bd/dfx_controller_setup/ip/dfx_controller_setup_s00_data_fifo_0/dfx_controller_setup_s00_data_fifo_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==dfx_controller_setup_s00_data_fifo_0 || ORIG_REF_NAME==dfx_controller_setup_s00_data_fifo_0} -quiet] -quiet

# XDC: bd/dfx_controller_setup/dfx_controller_setup_ooc.xdc
