# This file is automatically generated.
# It contains HD.RECONFIGURABLE settings for all instances of partition_def.

set_property HD.RECONFIGURABLE 1 -quiet [get_cells -hier -filter {ORIG_REF_NAME == light_count_mod || REF_NAME == light_count_mod}]
