# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_msg_config -id {Physopt 32-662} -limit 9999
set_msg_config -id {Physopt 32-668} -limit 9999
set_msg_config -id {Physopt 32-702} -limit 9999
set_msg_config -id {Synth 8-256} -limit 10000
set_msg_config -id {Synth 8-638} -limit 10000
create_project -in_memory -part xc7a200tsbg484-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir D:/Entertaiment/Programy/VHDL/VHDL/CustomFloorplanTest/CustomFloorplanTest.cache/wt [current_project]
set_property parent.project_path D:/Entertaiment/Programy/VHDL/VHDL/CustomFloorplanTest/CustomFloorplanTest.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property board_part digilentinc.com:nexys_video:part0:1.1 [current_project]
set_property ip_output_repo d:/Entertaiment/Programy/VHDL/VHDL/CustomFloorplanTest/CustomFloorplanTest.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
add_files -quiet D:/Entertaiment/Programy/VHDL/VHDL/CustomFloorplanTest/CustomFloorplanTest.runs/light_count_mod_synth_1/light_count_mod.dcp
set_property used_in_implementation false [get_files D:/Entertaiment/Programy/VHDL/VHDL/CustomFloorplanTest/CustomFloorplanTest.runs/light_count_mod_synth_1/light_count_mod.dcp]
read_xdc hd_reconfig.xdc
set_property used_in_implementation false [get_files hd_reconfig.xdc]
read_vhdl -library xil_defaultlib {
  D:/Entertaiment/Programy/VHDL/VHDL/CustomFloorplanTest/CustomFloorplanTest.srcs/sources_1/new/clock_generator.vhd
  D:/Entertaiment/Programy/VHDL/VHDL/CustomFloorplanTest/CustomFloorplanTest.srcs/sources_1/new/top.vhd
}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc D:/Entertaiment/Programy/VHDL/VHDL/CustomFloorplanTest/CustomFloorplanTest.srcs/constrs_1/imports/VHDL/Nexys-Video-Master.xdc
set_property used_in_implementation false [get_files D:/Entertaiment/Programy/VHDL/VHDL/CustomFloorplanTest/CustomFloorplanTest.srcs/constrs_1/imports/VHDL/Nexys-Video-Master.xdc]

set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top top -part xc7a200tsbg484-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef top.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file top_utilization_synth.rpt -pb top_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
