# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/Entertaiment/Programy/VHDL/VHDL/PartialReconfigSimple/CustomFloorplanTest.srcs/sources_1/bd/dfx_controller_setup/ip/dfx_controller_setup_rst_sys_clock_50M_0/dfx_controller_setup_rst_sys_clock_50M_0.xci
# IP: The module: 'dfx_controller_setup_rst_sys_clock_50M_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Entertaiment/Programy/VHDL/VHDL/PartialReconfigSimple/CustomFloorplanTest.srcs/sources_1/bd/dfx_controller_setup/ip/dfx_controller_setup_rst_sys_clock_50M_0/dfx_controller_setup_rst_sys_clock_50M_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'dfx_controller_setup_rst_sys_clock_50M_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: d:/Entertaiment/Programy/VHDL/VHDL/PartialReconfigSimple/CustomFloorplanTest.srcs/sources_1/bd/dfx_controller_setup/ip/dfx_controller_setup_rst_sys_clock_50M_0/dfx_controller_setup_rst_sys_clock_50M_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'dfx_controller_setup_rst_sys_clock_50M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: d:/Entertaiment/Programy/VHDL/VHDL/PartialReconfigSimple/CustomFloorplanTest.srcs/sources_1/bd/dfx_controller_setup/ip/dfx_controller_setup_rst_sys_clock_50M_0/dfx_controller_setup_rst_sys_clock_50M_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'dfx_controller_setup_rst_sys_clock_50M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: d:/Entertaiment/Programy/VHDL/VHDL/PartialReconfigSimple/CustomFloorplanTest.srcs/sources_1/bd/dfx_controller_setup/ip/dfx_controller_setup_rst_sys_clock_50M_0/dfx_controller_setup_rst_sys_clock_50M_0.xci
# IP: The module: 'dfx_controller_setup_rst_sys_clock_50M_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Entertaiment/Programy/VHDL/VHDL/PartialReconfigSimple/CustomFloorplanTest.srcs/sources_1/bd/dfx_controller_setup/ip/dfx_controller_setup_rst_sys_clock_50M_0/dfx_controller_setup_rst_sys_clock_50M_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'dfx_controller_setup_rst_sys_clock_50M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: d:/Entertaiment/Programy/VHDL/VHDL/PartialReconfigSimple/CustomFloorplanTest.srcs/sources_1/bd/dfx_controller_setup/ip/dfx_controller_setup_rst_sys_clock_50M_0/dfx_controller_setup_rst_sys_clock_50M_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'dfx_controller_setup_rst_sys_clock_50M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: d:/Entertaiment/Programy/VHDL/VHDL/PartialReconfigSimple/CustomFloorplanTest.srcs/sources_1/bd/dfx_controller_setup/ip/dfx_controller_setup_rst_sys_clock_50M_0/dfx_controller_setup_rst_sys_clock_50M_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'dfx_controller_setup_rst_sys_clock_50M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
