# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/Entertaiment/Programy/VHDL/VHDL/PartialReconfigSimple/MEMcontroller/MEMcontroller.srcs/sources_1/bd/design_1/ip/design_1_rst_clk_wiz_0_100M_5/design_1_rst_clk_wiz_0_100M_5.xci
# IP: The module: 'design_1_rst_clk_wiz_0_100M_5' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Entertaiment/Programy/VHDL/VHDL/PartialReconfigSimple/MEMcontroller/MEMcontroller.srcs/sources_1/bd/design_1/ip/design_1_rst_clk_wiz_0_100M_5/design_1_rst_clk_wiz_0_100M_5_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_rst_clk_wiz_0_100M_5'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: d:/Entertaiment/Programy/VHDL/VHDL/PartialReconfigSimple/MEMcontroller/MEMcontroller.srcs/sources_1/bd/design_1/ip/design_1_rst_clk_wiz_0_100M_5/design_1_rst_clk_wiz_0_100M_5.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_rst_clk_wiz_0_100M_5'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: d:/Entertaiment/Programy/VHDL/VHDL/PartialReconfigSimple/MEMcontroller/MEMcontroller.srcs/sources_1/bd/design_1/ip/design_1_rst_clk_wiz_0_100M_5/design_1_rst_clk_wiz_0_100M_5_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_rst_clk_wiz_0_100M_5'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: d:/Entertaiment/Programy/VHDL/VHDL/PartialReconfigSimple/MEMcontroller/MEMcontroller.srcs/sources_1/bd/design_1/ip/design_1_rst_clk_wiz_0_100M_5/design_1_rst_clk_wiz_0_100M_5.xci
# IP: The module: 'design_1_rst_clk_wiz_0_100M_5' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Entertaiment/Programy/VHDL/VHDL/PartialReconfigSimple/MEMcontroller/MEMcontroller.srcs/sources_1/bd/design_1/ip/design_1_rst_clk_wiz_0_100M_5/design_1_rst_clk_wiz_0_100M_5_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_rst_clk_wiz_0_100M_5'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: d:/Entertaiment/Programy/VHDL/VHDL/PartialReconfigSimple/MEMcontroller/MEMcontroller.srcs/sources_1/bd/design_1/ip/design_1_rst_clk_wiz_0_100M_5/design_1_rst_clk_wiz_0_100M_5.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_rst_clk_wiz_0_100M_5'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: d:/Entertaiment/Programy/VHDL/VHDL/PartialReconfigSimple/MEMcontroller/MEMcontroller.srcs/sources_1/bd/design_1/ip/design_1_rst_clk_wiz_0_100M_5/design_1_rst_clk_wiz_0_100M_5_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_rst_clk_wiz_0_100M_5'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
