# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param chipscope.maxJobs 4
set_param xicom.use_bs_reader 1
set_msg_config  -id {[BD 41-1306]}  -suppress 
set_msg_config  -id {[BD 41-1271]}  -suppress 
create_project -in_memory -part xc7a200tsbg484-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir D:/Entertaiment/Programy/VHDL/VHDL/Display/Display.cache/wt [current_project]
set_property parent.project_path D:/Entertaiment/Programy/VHDL/VHDL/Display/Display.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_FIFO XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property board_part digilentinc.com:nexys_video:part0:1.1 [current_project]
set_property ip_repo_paths e:/Xilinx/vivado-library-master [current_project]
update_ip_catalog
set_property ip_output_repo d:/Entertaiment/Programy/VHDL/VHDL/Display/Display.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_vhdl -library xil_defaultlib D:/Entertaiment/Programy/VHDL/VHDL/Display/Display.srcs/sources_1/bd/design_1/hdl/design_1_wrapper.vhd
add_files D:/Entertaiment/Programy/VHDL/VHDL/Display/Display.srcs/sources_1/bd/design_1/design_1.bd
set_property used_in_implementation false [get_files -all d:/Entertaiment/Programy/VHDL/VHDL/Display/Display.srcs/sources_1/bd/design_1/ip/design_1_axi_gpio_0_0_1/design_1_axi_gpio_0_0_board.xdc]
set_property used_in_implementation false [get_files -all d:/Entertaiment/Programy/VHDL/VHDL/Display/Display.srcs/sources_1/bd/design_1/ip/design_1_axi_gpio_0_0_1/design_1_axi_gpio_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Entertaiment/Programy/VHDL/VHDL/Display/Display.srcs/sources_1/bd/design_1/ip/design_1_axi_gpio_0_0_1/design_1_axi_gpio_0_0.xdc]
set_property used_in_implementation false [get_files -all d:/Entertaiment/Programy/VHDL/VHDL/Display/Display.srcs/sources_1/bd/design_1/ip/design_1_clk_wiz_0_0_1/design_1_clk_wiz_0_0_board.xdc]
set_property used_in_implementation false [get_files -all d:/Entertaiment/Programy/VHDL/VHDL/Display/Display.srcs/sources_1/bd/design_1/ip/design_1_clk_wiz_0_0_1/design_1_clk_wiz_0_0.xdc]
set_property used_in_implementation false [get_files -all d:/Entertaiment/Programy/VHDL/VHDL/Display/Display.srcs/sources_1/bd/design_1/ip/design_1_clk_wiz_0_0_1/design_1_clk_wiz_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Entertaiment/Programy/VHDL/VHDL/Display/Display.srcs/sources_1/bd/design_1/ip/design_1_PmodMTDS_0_2/src/PmodMTDS_pmod_bridge_0_0/PmodMTDS_pmod_bridge_0_0_board.xdc]
set_property used_in_implementation false [get_files -all d:/Entertaiment/Programy/VHDL/VHDL/Display/Display.srcs/sources_1/bd/design_1/ip/design_1_PmodMTDS_0_2/src/PmodMTDS_pmod_bridge_0_0/src/pmod_concat_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Entertaiment/Programy/VHDL/VHDL/Display/Display.srcs/sources_1/bd/design_1/ip/design_1_PmodMTDS_0_2/design_1_PmodMTDS_0_2_board.xdc]
set_property used_in_implementation false [get_files -all d:/Entertaiment/Programy/VHDL/VHDL/Display/Display.srcs/sources_1/bd/design_1/ip/design_1_PmodMTDS_0_2/src/PmodMTDS_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Entertaiment/Programy/VHDL/VHDL/Display/Display.srcs/sources_1/bd/design_1/ip/design_1_PmodMTDS_0_2/src/PmodMTDS_axi_quad_spi_0_0/PmodMTDS_axi_quad_spi_0_0_board.xdc]
set_property used_in_implementation false [get_files -all d:/Entertaiment/Programy/VHDL/VHDL/Display/Display.srcs/sources_1/bd/design_1/ip/design_1_PmodMTDS_0_2/src/PmodMTDS_axi_quad_spi_0_0/PmodMTDS_axi_quad_spi_0_0.xdc]
set_property used_in_implementation false [get_files -all d:/Entertaiment/Programy/VHDL/VHDL/Display/Display.srcs/sources_1/bd/design_1/ip/design_1_PmodMTDS_0_2/src/PmodMTDS_axi_quad_spi_0_0/PmodMTDS_axi_quad_spi_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Entertaiment/Programy/VHDL/VHDL/Display/Display.srcs/sources_1/bd/design_1/ip/design_1_PmodMTDS_0_2/src/PmodMTDS_axi_quad_spi_0_0/PmodMTDS_axi_quad_spi_0_0_clocks.xdc]
set_property used_in_implementation false [get_files -all d:/Entertaiment/Programy/VHDL/VHDL/Display/Display.srcs/sources_1/bd/design_1/ip/design_1_PmodMTDS_0_2/src/PmodMTDS_axi_gpio_0_0/PmodMTDS_axi_gpio_0_0_board.xdc]
set_property used_in_implementation false [get_files -all d:/Entertaiment/Programy/VHDL/VHDL/Display/Display.srcs/sources_1/bd/design_1/ip/design_1_PmodMTDS_0_2/src/PmodMTDS_axi_gpio_0_0/PmodMTDS_axi_gpio_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Entertaiment/Programy/VHDL/VHDL/Display/Display.srcs/sources_1/bd/design_1/ip/design_1_PmodMTDS_0_2/src/PmodMTDS_axi_gpio_0_0/PmodMTDS_axi_gpio_0_0.xdc]
set_property used_in_implementation false [get_files -all d:/Entertaiment/Programy/VHDL/VHDL/Display/Display.srcs/sources_1/bd/design_1/ip/design_1_PmodMTDS_0_2/src/axi_timer_0/axi_timer_0.xdc]
set_property used_in_implementation false [get_files -all d:/Entertaiment/Programy/VHDL/VHDL/Display/Display.srcs/sources_1/bd/design_1/ip/design_1_PmodMTDS_0_2/src/axi_timer_0/axi_timer_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Entertaiment/Programy/VHDL/VHDL/Display/Display.srcs/sources_1/bd/design_1/ip/design_1_microblaze_0_4/design_1_microblaze_0_4.xdc]
set_property used_in_implementation false [get_files -all d:/Entertaiment/Programy/VHDL/VHDL/Display/Display.srcs/sources_1/bd/design_1/ip/design_1_microblaze_0_4/design_1_microblaze_0_4_ooc_debug.xdc]
set_property used_in_implementation false [get_files -all d:/Entertaiment/Programy/VHDL/VHDL/Display/Display.srcs/sources_1/bd/design_1/ip/design_1_microblaze_0_4/design_1_microblaze_0_4_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Entertaiment/Programy/VHDL/VHDL/Display/Display.srcs/sources_1/bd/design_1/ip/design_1_dlmb_v10_3/design_1_dlmb_v10_3.xdc]
set_property used_in_implementation false [get_files -all d:/Entertaiment/Programy/VHDL/VHDL/Display/Display.srcs/sources_1/bd/design_1/ip/design_1_dlmb_v10_3/design_1_dlmb_v10_3_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Entertaiment/Programy/VHDL/VHDL/Display/Display.srcs/sources_1/bd/design_1/ip/design_1_ilmb_v10_3/design_1_ilmb_v10_3.xdc]
set_property used_in_implementation false [get_files -all d:/Entertaiment/Programy/VHDL/VHDL/Display/Display.srcs/sources_1/bd/design_1/ip/design_1_ilmb_v10_3/design_1_ilmb_v10_3_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Entertaiment/Programy/VHDL/VHDL/Display/Display.srcs/sources_1/bd/design_1/ip/design_1_dlmb_bram_if_cntlr_3/design_1_dlmb_bram_if_cntlr_3_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Entertaiment/Programy/VHDL/VHDL/Display/Display.srcs/sources_1/bd/design_1/ip/design_1_ilmb_bram_if_cntlr_3/design_1_ilmb_bram_if_cntlr_3_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Entertaiment/Programy/VHDL/VHDL/Display/Display.srcs/sources_1/bd/design_1/ip/design_1_lmb_bram_3/design_1_lmb_bram_3_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Entertaiment/Programy/VHDL/VHDL/Display/Display.srcs/sources_1/bd/design_1/ip/design_1_mdm_1_5/design_1_mdm_1_5.xdc]
set_property used_in_implementation false [get_files -all d:/Entertaiment/Programy/VHDL/VHDL/Display/Display.srcs/sources_1/bd/design_1/ip/design_1_mdm_1_5/design_1_mdm_1_5_ooc_trace.xdc]
set_property used_in_implementation false [get_files -all d:/Entertaiment/Programy/VHDL/VHDL/Display/Display.srcs/sources_1/bd/design_1/ip/design_1_rst_clk_wiz_0_100M_4/design_1_rst_clk_wiz_0_100M_4_board.xdc]
set_property used_in_implementation false [get_files -all d:/Entertaiment/Programy/VHDL/VHDL/Display/Display.srcs/sources_1/bd/design_1/ip/design_1_rst_clk_wiz_0_100M_4/design_1_rst_clk_wiz_0_100M_4.xdc]
set_property used_in_implementation false [get_files -all d:/Entertaiment/Programy/VHDL/VHDL/Display/Display.srcs/sources_1/bd/design_1/ip/design_1_rst_clk_wiz_0_100M_4/design_1_rst_clk_wiz_0_100M_4_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Entertaiment/Programy/VHDL/VHDL/Display/Display.srcs/sources_1/bd/design_1/ip/design_1_xbar_3/design_1_xbar_3_ooc.xdc]
set_property used_in_implementation false [get_files -all D:/Entertaiment/Programy/VHDL/VHDL/Display/Display.srcs/sources_1/bd/design_1/design_1_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Entertaiment/Programy/VHDL/VHDL/Display/Display.srcs/sources_1/bd/design_1/ip/design_1_microblaze_0_4/data/mb_bootloop_le.elf]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc D:/Entertaiment/Programy/VHDL/VHDL/Display/Display.srcs/constrs_1/imports/VHDL/Nexys-Video-Master.xdc
set_property used_in_implementation false [get_files D:/Entertaiment/Programy/VHDL/VHDL/Display/Display.srcs/constrs_1/imports/VHDL/Nexys-Video-Master.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top design_1_wrapper -part xc7a200tsbg484-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef design_1_wrapper.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file design_1_wrapper_utilization_synth.rpt -pb design_1_wrapper_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
