# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/VHDL/Nexys-Video-Master.xdc

# Block Designs: bd/design_1/design_1.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1 || ORIG_REF_NAME==design_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_gpio_0_0_1/design_1_axi_gpio_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_axi_gpio_0_0 || ORIG_REF_NAME==design_1_axi_gpio_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_clk_wiz_0_0_1/design_1_clk_wiz_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_clk_wiz_0_0 || ORIG_REF_NAME==design_1_clk_wiz_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_PmodMTDS_0_2/design_1_PmodMTDS_0_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_PmodMTDS_0_2 || ORIG_REF_NAME==design_1_PmodMTDS_0_2} -quiet] -quiet

# IP: bd/design_1/ip/design_1_microblaze_0_4/design_1_microblaze_0_4.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_microblaze_0_4 || ORIG_REF_NAME==design_1_microblaze_0_4} -quiet] -quiet

# IP: bd/design_1/ip/design_1_dlmb_v10_3/design_1_dlmb_v10_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_dlmb_v10_3 || ORIG_REF_NAME==design_1_dlmb_v10_3} -quiet] -quiet

# IP: bd/design_1/ip/design_1_ilmb_v10_3/design_1_ilmb_v10_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_ilmb_v10_3 || ORIG_REF_NAME==design_1_ilmb_v10_3} -quiet] -quiet

# IP: bd/design_1/ip/design_1_dlmb_bram_if_cntlr_3/design_1_dlmb_bram_if_cntlr_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_dlmb_bram_if_cntlr_3 || ORIG_REF_NAME==design_1_dlmb_bram_if_cntlr_3} -quiet] -quiet

# IP: bd/design_1/ip/design_1_ilmb_bram_if_cntlr_3/design_1_ilmb_bram_if_cntlr_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_ilmb_bram_if_cntlr_3 || ORIG_REF_NAME==design_1_ilmb_bram_if_cntlr_3} -quiet] -quiet

# IP: bd/design_1/ip/design_1_lmb_bram_3/design_1_lmb_bram_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_lmb_bram_3 || ORIG_REF_NAME==design_1_lmb_bram_3} -quiet] -quiet

# IP: bd/design_1/ip/design_1_mdm_1_5/design_1_mdm_1_5.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_mdm_1_5 || ORIG_REF_NAME==design_1_mdm_1_5} -quiet] -quiet

# IP: bd/design_1/ip/design_1_rst_clk_wiz_0_100M_4/design_1_rst_clk_wiz_0_100M_4.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_rst_clk_wiz_0_100M_4 || ORIG_REF_NAME==design_1_rst_clk_wiz_0_100M_4} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xbar_3/design_1_xbar_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_xbar_3 || ORIG_REF_NAME==design_1_xbar_3} -quiet] -quiet

# IP: bd/design_1/ip/design_1_microblaze_0_axi_periph_3/design_1_microblaze_0_axi_periph_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_microblaze_0_axi_periph_3 || ORIG_REF_NAME==design_1_microblaze_0_axi_periph_3} -quiet] -quiet

# XDC: bd/design_1/design_1_ooc.xdc
