# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/VHDL/Nexys-Video-Master.xdc

# Block Designs: bd/design_1/design_1.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1 || ORIG_REF_NAME==design_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_microblaze_0_6/design_1_microblaze_0_6.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_microblaze_0_6 || ORIG_REF_NAME==design_1_microblaze_0_6} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_hwicap_0_4/design_1_axi_hwicap_0_4.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_axi_hwicap_0_4 || ORIG_REF_NAME==design_1_axi_hwicap_0_4} -quiet] -quiet

# IP: bd/design_1/ip/design_1_mig_7series_0_5/design_1_mig_7series_0_5.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_mig_7series_0_5 || ORIG_REF_NAME==design_1_mig_7series_0_5} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_uartlite_0_4/design_1_axi_uartlite_0_4.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_axi_uartlite_0_4 || ORIG_REF_NAME==design_1_axi_uartlite_0_4} -quiet] -quiet

# IP: bd/design_1/ip/design_1_clk_wiz_0_3/design_1_clk_wiz_0_3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_clk_wiz_0_3 || ORIG_REF_NAME==design_1_clk_wiz_0_3} -quiet] -quiet

# IP: bd/design_1/ip/design_1_dlmb_v10_7/design_1_dlmb_v10_7.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_dlmb_v10_7 || ORIG_REF_NAME==design_1_dlmb_v10_7} -quiet] -quiet

# IP: bd/design_1/ip/design_1_ilmb_v10_7/design_1_ilmb_v10_7.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_ilmb_v10_7 || ORIG_REF_NAME==design_1_ilmb_v10_7} -quiet] -quiet

# IP: bd/design_1/ip/design_1_dlmb_bram_if_cntlr_7/design_1_dlmb_bram_if_cntlr_7.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_dlmb_bram_if_cntlr_7 || ORIG_REF_NAME==design_1_dlmb_bram_if_cntlr_7} -quiet] -quiet

# IP: bd/design_1/ip/design_1_ilmb_bram_if_cntlr_7/design_1_ilmb_bram_if_cntlr_7.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_ilmb_bram_if_cntlr_7 || ORIG_REF_NAME==design_1_ilmb_bram_if_cntlr_7} -quiet] -quiet

# IP: bd/design_1/ip/design_1_lmb_bram_7/design_1_lmb_bram_7.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_lmb_bram_7 || ORIG_REF_NAME==design_1_lmb_bram_7} -quiet] -quiet

# IP: bd/design_1/ip/design_1_mdm_1_5/design_1_mdm_1_5.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_mdm_1_5 || ORIG_REF_NAME==design_1_mdm_1_5} -quiet] -quiet

# IP: bd/design_1/ip/design_1_rst_clk_wiz_0_200M_1/design_1_rst_clk_wiz_0_200M_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_rst_clk_wiz_0_200M_1 || ORIG_REF_NAME==design_1_rst_clk_wiz_0_200M_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_reset_inv_0_4/design_1_reset_inv_0_4.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_reset_inv_0_4 || ORIG_REF_NAME==design_1_reset_inv_0_4} -quiet] -quiet

# IP: bd/design_1/ip/design_1_rst_mig_7series_0_100M_4/design_1_rst_mig_7series_0_100M_4.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_rst_mig_7series_0_100M_4 || ORIG_REF_NAME==design_1_rst_mig_7series_0_100M_4} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xbar_7/design_1_xbar_7.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_xbar_7 || ORIG_REF_NAME==design_1_xbar_7} -quiet] -quiet

# IP: bd/design_1/ip/design_1_microblaze_0_axi_periph_9/design_1_microblaze_0_axi_periph_9.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_microblaze_0_axi_periph_9 || ORIG_REF_NAME==design_1_microblaze_0_axi_periph_9} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_smc_5/design_1_axi_smc_5.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_axi_smc_5 || ORIG_REF_NAME==design_1_axi_smc_5} -quiet] -quiet

# IP: bd/design_1/ip/design_1_clk_wiz_0_4/design_1_clk_wiz_0_4.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_clk_wiz_0_4 || ORIG_REF_NAME==design_1_clk_wiz_0_4} -quiet] -quiet

# XDC: d:/Entertaiment/Programy/VHDL/PRBlaze/PRBlaze.gen/sources_1/bd/design_1/design_1_ooc.xdc
