# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: C:/git/Nexys-Video-HDMI/src/constraints/vdma_timing_workaround.xdc

# XDC: C:/git/Nexys-Video-HDMI/src/constraints/NexysVideo_Master.xdc

# Block Designs: bd/hdmi/hdmi.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hdmi || ORIG_REF_NAME==hdmi} -quiet] -quiet

# IP: bd/hdmi/ip/hdmi_axi_dynclk_0_0/hdmi_axi_dynclk_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hdmi_axi_dynclk_0_0 || ORIG_REF_NAME==hdmi_axi_dynclk_0_0} -quiet] -quiet

# IP: bd/hdmi/ip/hdmi_axi_gpio_video_0/hdmi_axi_gpio_video_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hdmi_axi_gpio_video_0 || ORIG_REF_NAME==hdmi_axi_gpio_video_0} -quiet] -quiet

# IP: bd/hdmi/ip/hdmi_axi_mem_intercon_0/hdmi_axi_mem_intercon_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hdmi_axi_mem_intercon_0 || ORIG_REF_NAME==hdmi_axi_mem_intercon_0} -quiet] -quiet

# IP: bd/hdmi/ip/hdmi_axi_timer_0_0/hdmi_axi_timer_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hdmi_axi_timer_0_0 || ORIG_REF_NAME==hdmi_axi_timer_0_0} -quiet] -quiet

# IP: bd/hdmi/ip/hdmi_axi_uartlite_0_0/hdmi_axi_uartlite_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hdmi_axi_uartlite_0_0 || ORIG_REF_NAME==hdmi_axi_uartlite_0_0} -quiet] -quiet

# IP: bd/hdmi/ip/hdmi_axi_vdma_0_0/hdmi_axi_vdma_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hdmi_axi_vdma_0_0 || ORIG_REF_NAME==hdmi_axi_vdma_0_0} -quiet] -quiet

# IP: bd/hdmi/ip/hdmi_dvi2rgb_0_0/hdmi_dvi2rgb_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hdmi_dvi2rgb_0_0 || ORIG_REF_NAME==hdmi_dvi2rgb_0_0} -quiet] -quiet

# IP: bd/hdmi/ip/hdmi_mdm_1_0/hdmi_mdm_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hdmi_mdm_1_0 || ORIG_REF_NAME==hdmi_mdm_1_0} -quiet] -quiet

# IP: bd/hdmi/ip/hdmi_microblaze_0_0/hdmi_microblaze_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hdmi_microblaze_0_0 || ORIG_REF_NAME==hdmi_microblaze_0_0} -quiet] -quiet

# IP: bd/hdmi/ip/hdmi_microblaze_0_axi_intc_0/hdmi_microblaze_0_axi_intc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hdmi_microblaze_0_axi_intc_0 || ORIG_REF_NAME==hdmi_microblaze_0_axi_intc_0} -quiet] -quiet

# IP: bd/hdmi/ip/hdmi_microblaze_0_axi_periph_0/hdmi_microblaze_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hdmi_microblaze_0_axi_periph_0 || ORIG_REF_NAME==hdmi_microblaze_0_axi_periph_0} -quiet] -quiet

# IP: bd/hdmi/ip/hdmi_microblaze_0_xlconcat_0/hdmi_microblaze_0_xlconcat_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hdmi_microblaze_0_xlconcat_0 || ORIG_REF_NAME==hdmi_microblaze_0_xlconcat_0} -quiet] -quiet

# IP: bd/hdmi/ip/hdmi_mig_7series_0_0/hdmi_mig_7series_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hdmi_mig_7series_0_0 || ORIG_REF_NAME==hdmi_mig_7series_0_0} -quiet] -quiet

# IP: bd/hdmi/ip/hdmi_rgb2dvi_0_0/hdmi_rgb2dvi_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hdmi_rgb2dvi_0_0 || ORIG_REF_NAME==hdmi_rgb2dvi_0_0} -quiet] -quiet

# IP: bd/hdmi/ip/hdmi_rst_mig_7series_0_100M_0/hdmi_rst_mig_7series_0_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hdmi_rst_mig_7series_0_100M_0 || ORIG_REF_NAME==hdmi_rst_mig_7series_0_100M_0} -quiet] -quiet

# IP: bd/hdmi/ip/hdmi_rst_mig_7series_0_pxl_0/hdmi_rst_mig_7series_0_pxl_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hdmi_rst_mig_7series_0_pxl_0 || ORIG_REF_NAME==hdmi_rst_mig_7series_0_pxl_0} -quiet] -quiet

# IP: bd/hdmi/ip/hdmi_v_axi4s_vid_out_0_0/hdmi_v_axi4s_vid_out_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hdmi_v_axi4s_vid_out_0_0 || ORIG_REF_NAME==hdmi_v_axi4s_vid_out_0_0} -quiet] -quiet

# IP: bd/hdmi/ip/hdmi_v_tc_0_0/hdmi_v_tc_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hdmi_v_tc_0_0 || ORIG_REF_NAME==hdmi_v_tc_0_0} -quiet] -quiet

# IP: bd/hdmi/ip/hdmi_v_tc_1_0/hdmi_v_tc_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hdmi_v_tc_1_0 || ORIG_REF_NAME==hdmi_v_tc_1_0} -quiet] -quiet

# IP: bd/hdmi/ip/hdmi_v_vid_in_axi4s_0_0/hdmi_v_vid_in_axi4s_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hdmi_v_vid_in_axi4s_0_0 || ORIG_REF_NAME==hdmi_v_vid_in_axi4s_0_0} -quiet] -quiet

# IP: bd/hdmi/ip/hdmi_xlconstant_0_0/hdmi_xlconstant_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hdmi_xlconstant_0_0 || ORIG_REF_NAME==hdmi_xlconstant_0_0} -quiet] -quiet

# IP: bd/hdmi/ip/hdmi_dlmb_bram_if_cntlr_0/hdmi_dlmb_bram_if_cntlr_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hdmi_dlmb_bram_if_cntlr_0 || ORIG_REF_NAME==hdmi_dlmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/hdmi/ip/hdmi_dlmb_v10_0/hdmi_dlmb_v10_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hdmi_dlmb_v10_0 || ORIG_REF_NAME==hdmi_dlmb_v10_0} -quiet] -quiet

# IP: bd/hdmi/ip/hdmi_ilmb_bram_if_cntlr_0/hdmi_ilmb_bram_if_cntlr_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hdmi_ilmb_bram_if_cntlr_0 || ORIG_REF_NAME==hdmi_ilmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/hdmi/ip/hdmi_ilmb_v10_0/hdmi_ilmb_v10_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hdmi_ilmb_v10_0 || ORIG_REF_NAME==hdmi_ilmb_v10_0} -quiet] -quiet

# IP: bd/hdmi/ip/hdmi_lmb_bram_0/hdmi_lmb_bram_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hdmi_lmb_bram_0 || ORIG_REF_NAME==hdmi_lmb_bram_0} -quiet] -quiet

# IP: bd/hdmi/ip/hdmi_xbar_1/hdmi_xbar_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hdmi_xbar_1 || ORIG_REF_NAME==hdmi_xbar_1} -quiet] -quiet

# IP: bd/hdmi/ip/hdmi_xbar_0/hdmi_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hdmi_xbar_0 || ORIG_REF_NAME==hdmi_xbar_0} -quiet] -quiet

# IP: bd/hdmi/ip/hdmi_m00_regslice_0/hdmi_m00_regslice_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hdmi_m00_regslice_0 || ORIG_REF_NAME==hdmi_m00_regslice_0} -quiet] -quiet

# IP: bd/hdmi/ip/hdmi_auto_ds_0/hdmi_auto_ds_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hdmi_auto_ds_0 || ORIG_REF_NAME==hdmi_auto_ds_0} -quiet] -quiet

# IP: bd/hdmi/ip/hdmi_auto_rs_w_0/hdmi_auto_rs_w_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hdmi_auto_rs_w_0 || ORIG_REF_NAME==hdmi_auto_rs_w_0} -quiet] -quiet

# IP: bd/hdmi/ip/hdmi_s03_regslice_0/hdmi_s03_regslice_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hdmi_s03_regslice_0 || ORIG_REF_NAME==hdmi_s03_regslice_0} -quiet] -quiet

# IP: bd/hdmi/ip/hdmi_s02_regslice_0/hdmi_s02_regslice_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hdmi_s02_regslice_0 || ORIG_REF_NAME==hdmi_s02_regslice_0} -quiet] -quiet

# IP: bd/hdmi/ip/hdmi_s01_regslice_0/hdmi_s01_regslice_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hdmi_s01_regslice_0 || ORIG_REF_NAME==hdmi_s01_regslice_0} -quiet] -quiet

# IP: bd/hdmi/ip/hdmi_auto_us_1/hdmi_auto_us_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hdmi_auto_us_1 || ORIG_REF_NAME==hdmi_auto_us_1} -quiet] -quiet

# IP: bd/hdmi/ip/hdmi_auto_rs_w_2/hdmi_auto_rs_w_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hdmi_auto_rs_w_2 || ORIG_REF_NAME==hdmi_auto_rs_w_2} -quiet] -quiet

# IP: bd/hdmi/ip/hdmi_s00_regslice_0/hdmi_s00_regslice_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hdmi_s00_regslice_0 || ORIG_REF_NAME==hdmi_s00_regslice_0} -quiet] -quiet

# IP: bd/hdmi/ip/hdmi_auto_us_0/hdmi_auto_us_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hdmi_auto_us_0 || ORIG_REF_NAME==hdmi_auto_us_0} -quiet] -quiet

# IP: bd/hdmi/ip/hdmi_auto_rs_w_1/hdmi_auto_rs_w_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hdmi_auto_rs_w_1 || ORIG_REF_NAME==hdmi_auto_rs_w_1} -quiet] -quiet

# XDC: bd/hdmi/hdmi_ooc.xdc
