# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param xicom.allow_cfgin_commands 0
set_param labtools.auto_update_hardware 0
create_project -in_memory -part xc7a200tsbg484-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir C:/git/Nexys-Video-HDMI/proj/Nexys-Video-HDMI.cache/wt [current_project]
set_property parent.project_path C:/git/Nexys-Video-HDMI/proj/Nexys-Video-HDMI.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_FIFO XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part_repo_paths C:/git/vivado-boards/new [current_project]
set_property board_part digilentinc.com:nexys_video:part0:1.1 [current_project]
set_property ip_repo_paths c:/git/Nexys-Video-HDMI/repo [current_project]
set_property ip_output_repo c:/git/Nexys-Video-HDMI/repo/cache [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib C:/git/Nexys-Video-HDMI/proj/Nexys-Video-HDMI.srcs/sources_1/imports/hdl/hdmi_wrapper.v
add_files C:/git/Nexys-Video-HDMI/proj/Nexys-Video-HDMI.srcs/sources_1/bd/hdmi/hdmi.bd
set_property used_in_implementation false [get_files -all c:/git/Nexys-Video-HDMI/proj/Nexys-Video-HDMI.srcs/sources_1/bd/hdmi/ip/hdmi_axi_gpio_video_0/hdmi_axi_gpio_video_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/git/Nexys-Video-HDMI/proj/Nexys-Video-HDMI.srcs/sources_1/bd/hdmi/ip/hdmi_axi_gpio_video_0/hdmi_axi_gpio_video_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/git/Nexys-Video-HDMI/proj/Nexys-Video-HDMI.srcs/sources_1/bd/hdmi/ip/hdmi_axi_gpio_video_0/hdmi_axi_gpio_video_0.xdc]
set_property used_in_implementation false [get_files -all c:/git/Nexys-Video-HDMI/proj/Nexys-Video-HDMI.srcs/sources_1/bd/hdmi/ip/hdmi_axi_timer_0_0/hdmi_axi_timer_0_0.xdc]
set_property used_in_implementation false [get_files -all c:/git/Nexys-Video-HDMI/proj/Nexys-Video-HDMI.srcs/sources_1/bd/hdmi/ip/hdmi_axi_timer_0_0/hdmi_axi_timer_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/git/Nexys-Video-HDMI/proj/Nexys-Video-HDMI.srcs/sources_1/bd/hdmi/ip/hdmi_axi_uartlite_0_0/hdmi_axi_uartlite_0_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/git/Nexys-Video-HDMI/proj/Nexys-Video-HDMI.srcs/sources_1/bd/hdmi/ip/hdmi_axi_uartlite_0_0/hdmi_axi_uartlite_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/git/Nexys-Video-HDMI/proj/Nexys-Video-HDMI.srcs/sources_1/bd/hdmi/ip/hdmi_axi_uartlite_0_0/hdmi_axi_uartlite_0_0.xdc]
set_property used_in_implementation false [get_files -all c:/git/Nexys-Video-HDMI/proj/Nexys-Video-HDMI.srcs/sources_1/bd/hdmi/ip/hdmi_axi_vdma_0_0/hdmi_axi_vdma_0_0.xdc]
set_property used_in_implementation false [get_files -all c:/git/Nexys-Video-HDMI/proj/Nexys-Video-HDMI.srcs/sources_1/bd/hdmi/ip/hdmi_axi_vdma_0_0/hdmi_axi_vdma_0_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/git/Nexys-Video-HDMI/proj/Nexys-Video-HDMI.srcs/sources_1/bd/hdmi/ip/hdmi_axi_vdma_0_0/hdmi_axi_vdma_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/git/Nexys-Video-HDMI/proj/Nexys-Video-HDMI.srcs/sources_1/bd/hdmi/ip/hdmi_dvi2rgb_0_0/src/ila_refclk/ila_v6_2/constraints/ila.xdc]
set_property used_in_implementation false [get_files -all c:/git/Nexys-Video-HDMI/proj/Nexys-Video-HDMI.srcs/sources_1/bd/hdmi/ip/hdmi_dvi2rgb_0_0/src/ila_refclk/ila_refclk_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/git/Nexys-Video-HDMI/proj/Nexys-Video-HDMI.srcs/sources_1/bd/hdmi/ip/hdmi_dvi2rgb_0_0/src/ila_pixclk/ila_v6_2/constraints/ila.xdc]
set_property used_in_implementation false [get_files -all c:/git/Nexys-Video-HDMI/proj/Nexys-Video-HDMI.srcs/sources_1/bd/hdmi/ip/hdmi_dvi2rgb_0_0/src/ila_pixclk/ila_pixclk_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/git/Nexys-Video-HDMI/proj/Nexys-Video-HDMI.srcs/sources_1/bd/hdmi/ip/hdmi_dvi2rgb_0_0/src/ila_timing_workaround.xdc]
set_property used_in_implementation false [get_files -all c:/git/Nexys-Video-HDMI/proj/Nexys-Video-HDMI.srcs/sources_1/bd/hdmi/ip/hdmi_dvi2rgb_0_0/src/dvi2rgb.xdc]
set_property used_in_implementation false [get_files -all c:/git/Nexys-Video-HDMI/proj/Nexys-Video-HDMI.srcs/sources_1/bd/hdmi/ip/hdmi_dvi2rgb_0_0/src/dvi2rgb_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/git/Nexys-Video-HDMI/proj/Nexys-Video-HDMI.srcs/sources_1/bd/hdmi/ip/hdmi_mdm_1_0/hdmi_mdm_1_0.xdc]
set_property used_in_implementation false [get_files -all c:/git/Nexys-Video-HDMI/proj/Nexys-Video-HDMI.srcs/sources_1/bd/hdmi/ip/hdmi_mdm_1_0/hdmi_mdm_1_0_ooc_trace.xdc]
set_property used_in_implementation false [get_files -all c:/git/Nexys-Video-HDMI/proj/Nexys-Video-HDMI.srcs/sources_1/bd/hdmi/ip/hdmi_microblaze_0_0/hdmi_microblaze_0_0.xdc]
set_property used_in_implementation false [get_files -all c:/git/Nexys-Video-HDMI/proj/Nexys-Video-HDMI.srcs/sources_1/bd/hdmi/ip/hdmi_microblaze_0_0/hdmi_microblaze_0_0_ooc_debug.xdc]
set_property used_in_implementation false [get_files -all c:/git/Nexys-Video-HDMI/proj/Nexys-Video-HDMI.srcs/sources_1/bd/hdmi/ip/hdmi_microblaze_0_0/hdmi_microblaze_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/git/Nexys-Video-HDMI/proj/Nexys-Video-HDMI.srcs/sources_1/bd/hdmi/ip/hdmi_microblaze_0_axi_intc_0/hdmi_microblaze_0_axi_intc_0.xdc]
set_property used_in_implementation false [get_files -all c:/git/Nexys-Video-HDMI/proj/Nexys-Video-HDMI.srcs/sources_1/bd/hdmi/ip/hdmi_microblaze_0_axi_intc_0/hdmi_microblaze_0_axi_intc_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/git/Nexys-Video-HDMI/proj/Nexys-Video-HDMI.srcs/sources_1/bd/hdmi/ip/hdmi_microblaze_0_axi_intc_0/hdmi_microblaze_0_axi_intc_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/git/Nexys-Video-HDMI/proj/Nexys-Video-HDMI.srcs/sources_1/bd/hdmi/ip/hdmi_mig_7series_0_0/hdmi_mig_7series_0_0/user_design/constraints/hdmi_mig_7series_0_0.xdc]
set_property used_in_implementation false [get_files -all c:/git/Nexys-Video-HDMI/proj/Nexys-Video-HDMI.srcs/sources_1/bd/hdmi/ip/hdmi_mig_7series_0_0/hdmi_mig_7series_0_0/user_design/constraints/hdmi_mig_7series_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/git/Nexys-Video-HDMI/proj/Nexys-Video-HDMI.srcs/sources_1/bd/hdmi/ip/hdmi_mig_7series_0_0/hdmi_mig_7series_0_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/git/Nexys-Video-HDMI/proj/Nexys-Video-HDMI.srcs/sources_1/bd/hdmi/ip/hdmi_rgb2dvi_0_0/src/rgb2dvi.xdc]
set_property used_in_implementation false [get_files -all c:/git/Nexys-Video-HDMI/proj/Nexys-Video-HDMI.srcs/sources_1/bd/hdmi/ip/hdmi_rgb2dvi_0_0/src/rgb2dvi_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/git/Nexys-Video-HDMI/proj/Nexys-Video-HDMI.srcs/sources_1/bd/hdmi/ip/hdmi_rgb2dvi_0_0/src/rgb2dvi_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/git/Nexys-Video-HDMI/proj/Nexys-Video-HDMI.srcs/sources_1/bd/hdmi/ip/hdmi_rst_mig_7series_0_100M_0/hdmi_rst_mig_7series_0_100M_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/git/Nexys-Video-HDMI/proj/Nexys-Video-HDMI.srcs/sources_1/bd/hdmi/ip/hdmi_rst_mig_7series_0_100M_0/hdmi_rst_mig_7series_0_100M_0.xdc]
set_property used_in_implementation false [get_files -all c:/git/Nexys-Video-HDMI/proj/Nexys-Video-HDMI.srcs/sources_1/bd/hdmi/ip/hdmi_rst_mig_7series_0_100M_0/hdmi_rst_mig_7series_0_100M_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/git/Nexys-Video-HDMI/proj/Nexys-Video-HDMI.srcs/sources_1/bd/hdmi/ip/hdmi_rst_mig_7series_0_pxl_0/hdmi_rst_mig_7series_0_pxl_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/git/Nexys-Video-HDMI/proj/Nexys-Video-HDMI.srcs/sources_1/bd/hdmi/ip/hdmi_rst_mig_7series_0_pxl_0/hdmi_rst_mig_7series_0_pxl_0.xdc]
set_property used_in_implementation false [get_files -all c:/git/Nexys-Video-HDMI/proj/Nexys-Video-HDMI.srcs/sources_1/bd/hdmi/ip/hdmi_rst_mig_7series_0_pxl_0/hdmi_rst_mig_7series_0_pxl_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/git/Nexys-Video-HDMI/proj/Nexys-Video-HDMI.srcs/sources_1/bd/hdmi/ip/hdmi_v_axi4s_vid_out_0_0/hdmi_v_axi4s_vid_out_0_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/git/Nexys-Video-HDMI/proj/Nexys-Video-HDMI.srcs/sources_1/bd/hdmi/ip/hdmi_v_axi4s_vid_out_0_0/hdmi_v_axi4s_vid_out_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/git/Nexys-Video-HDMI/proj/Nexys-Video-HDMI.srcs/sources_1/bd/hdmi/ip/hdmi_v_tc_0_0/hdmi_v_tc_0_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/git/Nexys-Video-HDMI/proj/Nexys-Video-HDMI.srcs/sources_1/bd/hdmi/ip/hdmi_v_tc_0_0/hdmi_v_tc_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/git/Nexys-Video-HDMI/proj/Nexys-Video-HDMI.srcs/sources_1/bd/hdmi/ip/hdmi_v_tc_1_0/hdmi_v_tc_1_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/git/Nexys-Video-HDMI/proj/Nexys-Video-HDMI.srcs/sources_1/bd/hdmi/ip/hdmi_v_tc_1_0/hdmi_v_tc_1_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/git/Nexys-Video-HDMI/proj/Nexys-Video-HDMI.srcs/sources_1/bd/hdmi/ip/hdmi_v_vid_in_axi4s_0_0/hdmi_v_vid_in_axi4s_0_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/git/Nexys-Video-HDMI/proj/Nexys-Video-HDMI.srcs/sources_1/bd/hdmi/ip/hdmi_v_vid_in_axi4s_0_0/hdmi_v_vid_in_axi4s_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/git/Nexys-Video-HDMI/proj/Nexys-Video-HDMI.srcs/sources_1/bd/hdmi/ip/hdmi_dlmb_bram_if_cntlr_0/hdmi_dlmb_bram_if_cntlr_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/git/Nexys-Video-HDMI/proj/Nexys-Video-HDMI.srcs/sources_1/bd/hdmi/ip/hdmi_dlmb_v10_0/hdmi_dlmb_v10_0.xdc]
set_property used_in_implementation false [get_files -all c:/git/Nexys-Video-HDMI/proj/Nexys-Video-HDMI.srcs/sources_1/bd/hdmi/ip/hdmi_dlmb_v10_0/hdmi_dlmb_v10_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/git/Nexys-Video-HDMI/proj/Nexys-Video-HDMI.srcs/sources_1/bd/hdmi/ip/hdmi_ilmb_bram_if_cntlr_0/hdmi_ilmb_bram_if_cntlr_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/git/Nexys-Video-HDMI/proj/Nexys-Video-HDMI.srcs/sources_1/bd/hdmi/ip/hdmi_ilmb_v10_0/hdmi_ilmb_v10_0.xdc]
set_property used_in_implementation false [get_files -all c:/git/Nexys-Video-HDMI/proj/Nexys-Video-HDMI.srcs/sources_1/bd/hdmi/ip/hdmi_ilmb_v10_0/hdmi_ilmb_v10_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/git/Nexys-Video-HDMI/proj/Nexys-Video-HDMI.srcs/sources_1/bd/hdmi/ip/hdmi_lmb_bram_0/hdmi_lmb_bram_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/git/Nexys-Video-HDMI/proj/Nexys-Video-HDMI.srcs/sources_1/bd/hdmi/ip/hdmi_xbar_1/hdmi_xbar_1_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/git/Nexys-Video-HDMI/proj/Nexys-Video-HDMI.srcs/sources_1/bd/hdmi/ip/hdmi_xbar_0/hdmi_xbar_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/git/Nexys-Video-HDMI/proj/Nexys-Video-HDMI.srcs/sources_1/bd/hdmi/ip/hdmi_m00_regslice_0/hdmi_m00_regslice_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/git/Nexys-Video-HDMI/proj/Nexys-Video-HDMI.srcs/sources_1/bd/hdmi/ip/hdmi_m00_regslice_0/hdmi_m00_regslice_0_ooc.xdc]
set_property used_in_synthesis false [get_files -all c:/git/Nexys-Video-HDMI/proj/Nexys-Video-HDMI.srcs/sources_1/bd/hdmi/ip/hdmi_auto_ds_0/hdmi_auto_ds_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/git/Nexys-Video-HDMI/proj/Nexys-Video-HDMI.srcs/sources_1/bd/hdmi/ip/hdmi_auto_ds_0/hdmi_auto_ds_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/git/Nexys-Video-HDMI/proj/Nexys-Video-HDMI.srcs/sources_1/bd/hdmi/ip/hdmi_auto_ds_0/hdmi_auto_ds_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/git/Nexys-Video-HDMI/proj/Nexys-Video-HDMI.srcs/sources_1/bd/hdmi/ip/hdmi_auto_rs_w_0/hdmi_auto_rs_w_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/git/Nexys-Video-HDMI/proj/Nexys-Video-HDMI.srcs/sources_1/bd/hdmi/ip/hdmi_auto_rs_w_0/hdmi_auto_rs_w_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/git/Nexys-Video-HDMI/proj/Nexys-Video-HDMI.srcs/sources_1/bd/hdmi/ip/hdmi_s03_regslice_0/hdmi_s03_regslice_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/git/Nexys-Video-HDMI/proj/Nexys-Video-HDMI.srcs/sources_1/bd/hdmi/ip/hdmi_s03_regslice_0/hdmi_s03_regslice_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/git/Nexys-Video-HDMI/proj/Nexys-Video-HDMI.srcs/sources_1/bd/hdmi/ip/hdmi_s02_regslice_0/hdmi_s02_regslice_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/git/Nexys-Video-HDMI/proj/Nexys-Video-HDMI.srcs/sources_1/bd/hdmi/ip/hdmi_s02_regslice_0/hdmi_s02_regslice_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/git/Nexys-Video-HDMI/proj/Nexys-Video-HDMI.srcs/sources_1/bd/hdmi/ip/hdmi_s01_regslice_0/hdmi_s01_regslice_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/git/Nexys-Video-HDMI/proj/Nexys-Video-HDMI.srcs/sources_1/bd/hdmi/ip/hdmi_s01_regslice_0/hdmi_s01_regslice_0_ooc.xdc]
set_property used_in_synthesis false [get_files -all c:/git/Nexys-Video-HDMI/proj/Nexys-Video-HDMI.srcs/sources_1/bd/hdmi/ip/hdmi_auto_us_1/hdmi_auto_us_1_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/git/Nexys-Video-HDMI/proj/Nexys-Video-HDMI.srcs/sources_1/bd/hdmi/ip/hdmi_auto_us_1/hdmi_auto_us_1_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/git/Nexys-Video-HDMI/proj/Nexys-Video-HDMI.srcs/sources_1/bd/hdmi/ip/hdmi_auto_us_1/hdmi_auto_us_1_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/git/Nexys-Video-HDMI/proj/Nexys-Video-HDMI.srcs/sources_1/bd/hdmi/ip/hdmi_auto_rs_w_2/hdmi_auto_rs_w_2_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/git/Nexys-Video-HDMI/proj/Nexys-Video-HDMI.srcs/sources_1/bd/hdmi/ip/hdmi_auto_rs_w_2/hdmi_auto_rs_w_2_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/git/Nexys-Video-HDMI/proj/Nexys-Video-HDMI.srcs/sources_1/bd/hdmi/ip/hdmi_s00_regslice_0/hdmi_s00_regslice_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/git/Nexys-Video-HDMI/proj/Nexys-Video-HDMI.srcs/sources_1/bd/hdmi/ip/hdmi_s00_regslice_0/hdmi_s00_regslice_0_ooc.xdc]
set_property used_in_synthesis false [get_files -all c:/git/Nexys-Video-HDMI/proj/Nexys-Video-HDMI.srcs/sources_1/bd/hdmi/ip/hdmi_auto_us_0/hdmi_auto_us_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/git/Nexys-Video-HDMI/proj/Nexys-Video-HDMI.srcs/sources_1/bd/hdmi/ip/hdmi_auto_us_0/hdmi_auto_us_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/git/Nexys-Video-HDMI/proj/Nexys-Video-HDMI.srcs/sources_1/bd/hdmi/ip/hdmi_auto_us_0/hdmi_auto_us_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/git/Nexys-Video-HDMI/proj/Nexys-Video-HDMI.srcs/sources_1/bd/hdmi/ip/hdmi_auto_rs_w_1/hdmi_auto_rs_w_1_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/git/Nexys-Video-HDMI/proj/Nexys-Video-HDMI.srcs/sources_1/bd/hdmi/ip/hdmi_auto_rs_w_1/hdmi_auto_rs_w_1_ooc.xdc]
set_property used_in_implementation false [get_files -all C:/git/Nexys-Video-HDMI/proj/Nexys-Video-HDMI.srcs/sources_1/bd/hdmi/hdmi_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/git/Nexys-Video-HDMI/src/constraints/vdma_timing_workaround.xdc
set_property used_in_implementation false [get_files C:/git/Nexys-Video-HDMI/src/constraints/vdma_timing_workaround.xdc]

read_xdc C:/git/Nexys-Video-HDMI/src/constraints/NexysVideo_Master.xdc
set_property used_in_implementation false [get_files C:/git/Nexys-Video-HDMI/src/constraints/NexysVideo_Master.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 0
close [open __synthesis_is_running__ w]

synth_design -top hdmi_wrapper -part xc7a200tsbg484-1 -flatten_hierarchy none -directive RuntimeOptimized -fsm_extraction off


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef hdmi_wrapper.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file hdmi_wrapper_utilization_synth.rpt -pb hdmi_wrapper_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
