# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
namespace eval ::optrace {
  variable script "D:/Entertaiment/Programy/VHDL/BlazeIt/BlazeIt.runs/synth_1/design_1_wrapper.tcl"
  variable category "vivado_synth"
}

# Try to connect to running dispatch if we haven't done so already.
# This code assumes that the Tcl interpreter is not using threads,
# since the ::dispatch::connected variable isn't mutex protected.
if {![info exists ::dispatch::connected]} {
  namespace eval ::dispatch {
    variable connected false
    if {[llength [array get env XILINX_CD_CONNECT_ID]] > 0} {
      set result "true"
      if {[catch {
        if {[lsearch -exact [package names] DispatchTcl] < 0} {
          set result [load librdi_cd_clienttcl[info sharedlibextension]] 
        }
        if {$result eq "false"} {
          puts "WARNING: Could not load dispatch client library"
        }
        set connect_id [ ::dispatch::init_client -mode EXISTING_SERVER ]
        if { $connect_id eq "" } {
          puts "WARNING: Could not initialize dispatch client"
        } else {
          puts "INFO: Dispatch client connection id - $connect_id"
          set connected true
        }
      } catch_res]} {
        puts "WARNING: failed to connect to dispatch server - $catch_res"
      }
    }
  }
}
if {$::dispatch::connected} {
  # Remove the dummy proc if it exists.
  if { [expr {[llength [info procs ::OPTRACE]] > 0}] } {
    rename ::OPTRACE ""
  }
  proc ::OPTRACE { task action {tags {} } } {
    ::vitis_log::op_trace "$task" $action -tags $tags -script $::optrace::script -category $::optrace::category
  }
  # dispatch is generic. We specifically want to attach logging.
  ::vitis_log::connect_client
} else {
  # Add dummy proc if it doesn't exist.
  if { [expr {[llength [info procs ::OPTRACE]] == 0}] } {
    proc ::OPTRACE {{arg1 \"\" } {arg2 \"\"} {arg3 \"\" } {arg4 \"\"} {arg5 \"\" } {arg6 \"\"}} {
        # Do nothing
    }
  }
}

proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
OPTRACE "synth_1" START { ROLLUP_AUTO }
set_param chipscope.maxJobs 4
set_msg_config  -id {[BD 41-1271]}  -suppress 
set_msg_config  -id {[BD 41-1306]}  -suppress 
OPTRACE "Creating in-memory project" START { }
create_project -in_memory -part xc7a200tsbg484-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir D:/Entertaiment/Programy/VHDL/BlazeIt/BlazeIt.cache/wt [current_project]
set_property parent.project_path D:/Entertaiment/Programy/VHDL/BlazeIt/BlazeIt.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property board_part digilentinc.com:nexys_video:part0:1.1 [current_project]
set_property ip_output_repo d:/Entertaiment/Programy/VHDL/BlazeIt/BlazeIt.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
OPTRACE "Creating in-memory project" END { }
OPTRACE "Adding files" START { }
read_vhdl -library xil_defaultlib D:/Entertaiment/Programy/VHDL/BlazeIt/BlazeIt.gen/sources_1/bd/design_1/hdl/design_1_wrapper.vhd
add_files D:/Entertaiment/Programy/VHDL/BlazeIt/BlazeIt.srcs/sources_1/bd/design_1/design_1.bd
set_property used_in_implementation false [get_files -all d:/Entertaiment/Programy/VHDL/BlazeIt/BlazeIt.gen/sources_1/bd/design_1/ip/design_1_microblaze_0_3/design_1_microblaze_0_3.xdc]
set_property used_in_implementation false [get_files -all d:/Entertaiment/Programy/VHDL/BlazeIt/BlazeIt.gen/sources_1/bd/design_1/ip/design_1_microblaze_0_3/design_1_microblaze_0_3_ooc_debug.xdc]
set_property used_in_implementation false [get_files -all d:/Entertaiment/Programy/VHDL/BlazeIt/BlazeIt.gen/sources_1/bd/design_1/ip/design_1_microblaze_0_3/design_1_microblaze_0_3_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Entertaiment/Programy/VHDL/BlazeIt/BlazeIt.gen/sources_1/bd/design_1/ip/design_1_clk_wiz_0_3/design_1_clk_wiz_0_3_board.xdc]
set_property used_in_implementation false [get_files -all d:/Entertaiment/Programy/VHDL/BlazeIt/BlazeIt.gen/sources_1/bd/design_1/ip/design_1_clk_wiz_0_3/design_1_clk_wiz_0_3.xdc]
set_property used_in_implementation false [get_files -all d:/Entertaiment/Programy/VHDL/BlazeIt/BlazeIt.gen/sources_1/bd/design_1/ip/design_1_clk_wiz_0_3/design_1_clk_wiz_0_3_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Entertaiment/Programy/VHDL/BlazeIt/BlazeIt.gen/sources_1/bd/design_1/ip/design_1_axi_gpio_0_3/design_1_axi_gpio_0_3_board.xdc]
set_property used_in_implementation false [get_files -all d:/Entertaiment/Programy/VHDL/BlazeIt/BlazeIt.gen/sources_1/bd/design_1/ip/design_1_axi_gpio_0_3/design_1_axi_gpio_0_3_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Entertaiment/Programy/VHDL/BlazeIt/BlazeIt.gen/sources_1/bd/design_1/ip/design_1_axi_gpio_0_3/design_1_axi_gpio_0_3.xdc]
set_property used_in_implementation false [get_files -all d:/Entertaiment/Programy/VHDL/BlazeIt/BlazeIt.gen/sources_1/bd/design_1/ip/design_1_dlmb_v10_3/design_1_dlmb_v10_3_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Entertaiment/Programy/VHDL/BlazeIt/BlazeIt.gen/sources_1/bd/design_1/ip/design_1_ilmb_v10_3/design_1_ilmb_v10_3_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Entertaiment/Programy/VHDL/BlazeIt/BlazeIt.gen/sources_1/bd/design_1/ip/design_1_dlmb_bram_if_cntlr_3/design_1_dlmb_bram_if_cntlr_3_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Entertaiment/Programy/VHDL/BlazeIt/BlazeIt.gen/sources_1/bd/design_1/ip/design_1_ilmb_bram_if_cntlr_3/design_1_ilmb_bram_if_cntlr_3_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Entertaiment/Programy/VHDL/BlazeIt/BlazeIt.gen/sources_1/bd/design_1/ip/design_1_lmb_bram_3/design_1_lmb_bram_3_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Entertaiment/Programy/VHDL/BlazeIt/BlazeIt.gen/sources_1/bd/design_1/ip/design_1_mdm_1_3/design_1_mdm_1_3.xdc]
set_property used_in_implementation false [get_files -all d:/Entertaiment/Programy/VHDL/BlazeIt/BlazeIt.gen/sources_1/bd/design_1/ip/design_1_mdm_1_3/design_1_mdm_1_3_ooc_trace.xdc]
set_property used_in_implementation false [get_files -all d:/Entertaiment/Programy/VHDL/BlazeIt/BlazeIt.gen/sources_1/bd/design_1/ip/design_1_rst_clk_wiz_0_100M_2/design_1_rst_clk_wiz_0_100M_2_board.xdc]
set_property used_in_implementation false [get_files -all d:/Entertaiment/Programy/VHDL/BlazeIt/BlazeIt.gen/sources_1/bd/design_1/ip/design_1_rst_clk_wiz_0_100M_2/design_1_rst_clk_wiz_0_100M_2.xdc]
set_property used_in_implementation false [get_files -all d:/Entertaiment/Programy/VHDL/BlazeIt/BlazeIt.gen/sources_1/bd/design_1/ip/design_1_rst_clk_wiz_0_100M_2/design_1_rst_clk_wiz_0_100M_2_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Entertaiment/Programy/VHDL/BlazeIt/BlazeIt.gen/sources_1/bd/design_1/ip/design_1_xbar_0/design_1_xbar_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Entertaiment/Programy/VHDL/BlazeIt/BlazeIt.gen/sources_1/bd/design_1/ip/design_1_axi_uartlite_0_0/design_1_axi_uartlite_0_0_board.xdc]
set_property used_in_implementation false [get_files -all d:/Entertaiment/Programy/VHDL/BlazeIt/BlazeIt.gen/sources_1/bd/design_1/ip/design_1_axi_uartlite_0_0/design_1_axi_uartlite_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Entertaiment/Programy/VHDL/BlazeIt/BlazeIt.gen/sources_1/bd/design_1/ip/design_1_axi_uartlite_0_0/design_1_axi_uartlite_0_0.xdc]
set_property used_in_implementation false [get_files -all d:/Entertaiment/Programy/VHDL/BlazeIt/BlazeIt.gen/sources_1/bd/design_1/ip/design_1_mig_7series_0_0/design_1_mig_7series_0_0/user_design/constraints/design_1_mig_7series_0_0.xdc]
set_property used_in_implementation false [get_files -all d:/Entertaiment/Programy/VHDL/BlazeIt/BlazeIt.gen/sources_1/bd/design_1/ip/design_1_mig_7series_0_0/design_1_mig_7series_0_0/user_design/constraints/design_1_mig_7series_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Entertaiment/Programy/VHDL/BlazeIt/BlazeIt.gen/sources_1/bd/design_1/ip/design_1_mig_7series_0_0/design_1_mig_7series_0_0_board.xdc]
set_property used_in_implementation false [get_files -all d:/Entertaiment/Programy/VHDL/BlazeIt/BlazeIt.gen/sources_1/bd/design_1/ip/design_1_rst_mig_7series_0_100M_0/design_1_rst_mig_7series_0_100M_0_board.xdc]
set_property used_in_implementation false [get_files -all d:/Entertaiment/Programy/VHDL/BlazeIt/BlazeIt.gen/sources_1/bd/design_1/ip/design_1_rst_mig_7series_0_100M_0/design_1_rst_mig_7series_0_100M_0.xdc]
set_property used_in_implementation false [get_files -all d:/Entertaiment/Programy/VHDL/BlazeIt/BlazeIt.gen/sources_1/bd/design_1/ip/design_1_rst_mig_7series_0_100M_0/design_1_rst_mig_7series_0_100M_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Entertaiment/Programy/VHDL/BlazeIt/BlazeIt.gen/sources_1/bd/design_1/ip/design_1_clk_wiz_0_4/design_1_clk_wiz_0_4_board.xdc]
set_property used_in_implementation false [get_files -all d:/Entertaiment/Programy/VHDL/BlazeIt/BlazeIt.gen/sources_1/bd/design_1/ip/design_1_clk_wiz_0_4/design_1_clk_wiz_0_4.xdc]
set_property used_in_implementation false [get_files -all d:/Entertaiment/Programy/VHDL/BlazeIt/BlazeIt.gen/sources_1/bd/design_1/ip/design_1_clk_wiz_0_4/design_1_clk_wiz_0_4_ooc.xdc]
set_property used_in_synthesis false [get_files -all d:/Entertaiment/Programy/VHDL/BlazeIt/BlazeIt.gen/sources_1/bd/design_1/ip/design_1_auto_cc_0/design_1_auto_cc_0_clocks.xdc]
set_property used_in_implementation false [get_files -all d:/Entertaiment/Programy/VHDL/BlazeIt/BlazeIt.gen/sources_1/bd/design_1/ip/design_1_auto_cc_0/design_1_auto_cc_0_clocks.xdc]
set_property used_in_implementation false [get_files -all d:/Entertaiment/Programy/VHDL/BlazeIt/BlazeIt.gen/sources_1/bd/design_1/ip/design_1_auto_cc_0/design_1_auto_cc_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Entertaiment/Programy/VHDL/BlazeIt/BlazeIt.gen/sources_1/bd/design_1/ip/design_1_auto_pc_0/design_1_auto_pc_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Entertaiment/Programy/VHDL/BlazeIt/BlazeIt.gen/sources_1/bd/design_1/design_1_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Entertaiment/Programy/VHDL/BlazeIt/BlazeIt.gen/sources_1/bd/design_1/ip/design_1_microblaze_0_3/data/mb_bootloop_le.elf]

OPTRACE "Adding files" END { }
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc D:/Entertaiment/Programy/VHDL/BlazeIt/BlazeIt.srcs/constrs_1/imports/VHDL/Nexys-Video-Master.xdc
set_property used_in_implementation false [get_files D:/Entertaiment/Programy/VHDL/BlazeIt/BlazeIt.srcs/constrs_1/imports/VHDL/Nexys-Video-Master.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

OPTRACE "synth_design" START { }
synth_design -top design_1_wrapper -part xc7a200tsbg484-1
OPTRACE "synth_design" END { }
if { [get_msg_config -count -severity {CRITICAL WARNING}] > 0 } {
 send_msg_id runtcl-6 info "Synthesis results are not added to the cache due to CRITICAL_WARNING"
}


OPTRACE "write_checkpoint" START { CHECKPOINT }
# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef design_1_wrapper.dcp
OPTRACE "write_checkpoint" END { }
OPTRACE "synth reports" START { REPORT }
create_report "synth_1_synth_report_utilization_0" "report_utilization -file design_1_wrapper_utilization_synth.rpt -pb design_1_wrapper_utilization_synth.pb"
OPTRACE "synth reports" END { }
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
OPTRACE "synth_1" END { }
