# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/Entertaiment/Programy/VHDL/VHDL/PartialReconfigSimple/CustomFloorplanTest.srcs/sources_1/bd/dfx_controller_setup/ip/dfx_controller_setup_ila_0_1/dfx_controller_setup_ila_0_1.xci
# IP: The module: 'dfx_controller_setup_ila_0_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Entertaiment/Programy/VHDL/VHDL/PartialReconfigSimple/CustomFloorplanTest.srcs/sources_1/bd/dfx_controller_setup/ip/dfx_controller_setup_ila_0_1/ila_v6_2/constraints/ila_impl.xdc
# XDC: The top module name and the constraint reference have the same name: 'dfx_controller_setup_ila_0_1'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: d:/Entertaiment/Programy/VHDL/VHDL/PartialReconfigSimple/CustomFloorplanTest.srcs/sources_1/bd/dfx_controller_setup/ip/dfx_controller_setup_ila_0_1/ila_v6_2/constraints/ila.xdc
# XDC: The top module name and the constraint reference have the same name: 'dfx_controller_setup_ila_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: d:/Entertaiment/Programy/VHDL/VHDL/PartialReconfigSimple/CustomFloorplanTest.srcs/sources_1/bd/dfx_controller_setup/ip/dfx_controller_setup_ila_0_1/dfx_controller_setup_ila_0_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'dfx_controller_setup_ila_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: d:/Entertaiment/Programy/VHDL/VHDL/PartialReconfigSimple/CustomFloorplanTest.srcs/sources_1/bd/dfx_controller_setup/ip/dfx_controller_setup_ila_0_1/dfx_controller_setup_ila_0_1.xci
# IP: The module: 'dfx_controller_setup_ila_0_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Entertaiment/Programy/VHDL/VHDL/PartialReconfigSimple/CustomFloorplanTest.srcs/sources_1/bd/dfx_controller_setup/ip/dfx_controller_setup_ila_0_1/ila_v6_2/constraints/ila_impl.xdc
# XDC: The top module name and the constraint reference have the same name: 'dfx_controller_setup_ila_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: d:/Entertaiment/Programy/VHDL/VHDL/PartialReconfigSimple/CustomFloorplanTest.srcs/sources_1/bd/dfx_controller_setup/ip/dfx_controller_setup_ila_0_1/ila_v6_2/constraints/ila.xdc
# XDC: The top module name and the constraint reference have the same name: 'dfx_controller_setup_ila_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: d:/Entertaiment/Programy/VHDL/VHDL/PartialReconfigSimple/CustomFloorplanTest.srcs/sources_1/bd/dfx_controller_setup/ip/dfx_controller_setup_ila_0_1/dfx_controller_setup_ila_0_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'dfx_controller_setup_ila_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
