# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/Entertaiment/Programy/VHDL/HDMIController/HDMIController.srcs/sources_1/ip/clk_25MHz/clk_25MHz.xci
# IP: The module: 'clk_25MHz' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Entertaiment/Programy/VHDL/HDMIController/HDMIController.gen/sources_1/ip/clk_25MHz/clk_25MHz_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_25MHz'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: d:/Entertaiment/Programy/VHDL/HDMIController/HDMIController.gen/sources_1/ip/clk_25MHz/clk_25MHz.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_25MHz'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: d:/Entertaiment/Programy/VHDL/HDMIController/HDMIController.gen/sources_1/ip/clk_25MHz/clk_25MHz_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_25MHz'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: d:/Entertaiment/Programy/VHDL/HDMIController/HDMIController.srcs/sources_1/ip/clk_25MHz/clk_25MHz.xci
# IP: The module: 'clk_25MHz' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Entertaiment/Programy/VHDL/HDMIController/HDMIController.gen/sources_1/ip/clk_25MHz/clk_25MHz_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_25MHz'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: d:/Entertaiment/Programy/VHDL/HDMIController/HDMIController.gen/sources_1/ip/clk_25MHz/clk_25MHz.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_25MHz'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: d:/Entertaiment/Programy/VHDL/HDMIController/HDMIController.gen/sources_1/ip/clk_25MHz/clk_25MHz_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_25MHz'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
