# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/Desktop/Nexys-Video-Master.xdc

# Block Designs: bd/design_1/design_1.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1 || ORIG_REF_NAME==design_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_quad_spi_0_1/design_1_axi_quad_spi_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_axi_quad_spi_0_1 || ORIG_REF_NAME==design_1_axi_quad_spi_0_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_dfx_controller_0_0/design_1_dfx_controller_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_dfx_controller_0_0 || ORIG_REF_NAME==design_1_dfx_controller_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_clk_wiz_0_0/design_1_clk_wiz_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_clk_wiz_0_0 || ORIG_REF_NAME==design_1_clk_wiz_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_protocol_convert_0_0/design_1_axi_protocol_convert_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_axi_protocol_convert_0_0 || ORIG_REF_NAME==design_1_axi_protocol_convert_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_protocol_convert_1_0/design_1_axi_protocol_convert_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_axi_protocol_convert_1_0 || ORIG_REF_NAME==design_1_axi_protocol_convert_1_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_rst_clk_wiz_0_100M_5/design_1_rst_clk_wiz_0_100M_5.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_rst_clk_wiz_0_100M_5 || ORIG_REF_NAME==design_1_rst_clk_wiz_0_100M_5} -quiet] -quiet

# IP: bd/design_1/ip/design_1_reset_inv_0_5/design_1_reset_inv_0_5.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_reset_inv_0_5 || ORIG_REF_NAME==design_1_reset_inv_0_5} -quiet] -quiet

# XDC: bd/design_1/design_1_ooc.xdc
