# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/constraints/NexysVideo_Master.xdc

# IP: ip/charLib/charLib.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==charLib || ORIG_REF_NAME==charLib} -quiet] -quiet

# IP: ip/mig_7series_0/mig_7series_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mig_7series_0 || ORIG_REF_NAME==mig_7series_0} -quiet] -quiet
