# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/Entertaiment/Programy/VHDL/VHDL/Display/Display.srcs/sources_1/bd/design_1/ip/design_1_PmodMTDS_0_2/design_1_PmodMTDS_0_2.xci
# IP: The module: 'design_1_PmodMTDS_0_2' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: d:/Entertaiment/Programy/VHDL/VHDL/Display/Display.srcs/sources_1/bd/design_1/ip/design_1_PmodMTDS_0_2/src/PmodMTDS_pmod_bridge_0_0/PmodMTDS_pmod_bridge_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==PmodMTDS_pmod_bridge_0_0 || ORIG_REF_NAME==PmodMTDS_pmod_bridge_0_0} -quiet] -quiet

# IP: d:/Entertaiment/Programy/VHDL/VHDL/Display/Display.srcs/sources_1/bd/design_1/ip/design_1_PmodMTDS_0_2/src/PmodMTDS_axi_quad_spi_0_0/PmodMTDS_axi_quad_spi_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==PmodMTDS_axi_quad_spi_0_0 || ORIG_REF_NAME==PmodMTDS_axi_quad_spi_0_0} -quiet] -quiet

# IP: d:/Entertaiment/Programy/VHDL/VHDL/Display/Display.srcs/sources_1/bd/design_1/ip/design_1_PmodMTDS_0_2/src/PmodMTDS_axi_gpio_0_0/PmodMTDS_axi_gpio_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==PmodMTDS_axi_gpio_0_0 || ORIG_REF_NAME==PmodMTDS_axi_gpio_0_0} -quiet] -quiet

# IP: d:/Entertaiment/Programy/VHDL/VHDL/Display/Display.srcs/sources_1/bd/design_1/ip/design_1_PmodMTDS_0_2/src/axi_timer_0/axi_timer_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==axi_timer_0 || ORIG_REF_NAME==axi_timer_0} -quiet] -quiet

# XDC: d:/Entertaiment/Programy/VHDL/VHDL/Display/Display.srcs/sources_1/bd/design_1/ip/design_1_PmodMTDS_0_2/src/PmodMTDS_pmod_bridge_0_0/PmodMTDS_pmod_bridge_0_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==PmodMTDS_pmod_bridge_0_0 || ORIG_REF_NAME==PmodMTDS_pmod_bridge_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: d:/Entertaiment/Programy/VHDL/VHDL/Display/Display.srcs/sources_1/bd/design_1/ip/design_1_PmodMTDS_0_2/src/PmodMTDS_pmod_bridge_0_0/src/pmod_concat_ooc.xdc

# XDC: d:/Entertaiment/Programy/VHDL/VHDL/Display/Display.srcs/sources_1/bd/design_1/ip/design_1_PmodMTDS_0_2/design_1_PmodMTDS_0_2_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_PmodMTDS_0_2'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: d:/Entertaiment/Programy/VHDL/VHDL/Display/Display.srcs/sources_1/bd/design_1/ip/design_1_PmodMTDS_0_2/src/PmodMTDS_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_PmodMTDS_0_2'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: d:/Entertaiment/Programy/VHDL/VHDL/Display/Display.srcs/sources_1/bd/design_1/ip/design_1_PmodMTDS_0_2/src/PmodMTDS_axi_quad_spi_0_0/PmodMTDS_axi_quad_spi_0_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==PmodMTDS_axi_quad_spi_0_0 || ORIG_REF_NAME==PmodMTDS_axi_quad_spi_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: d:/Entertaiment/Programy/VHDL/VHDL/Display/Display.srcs/sources_1/bd/design_1/ip/design_1_PmodMTDS_0_2/src/PmodMTDS_axi_quad_spi_0_0/PmodMTDS_axi_quad_spi_0_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==PmodMTDS_axi_quad_spi_0_0 || ORIG_REF_NAME==PmodMTDS_axi_quad_spi_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: d:/Entertaiment/Programy/VHDL/VHDL/Display/Display.srcs/sources_1/bd/design_1/ip/design_1_PmodMTDS_0_2/src/PmodMTDS_axi_quad_spi_0_0/PmodMTDS_axi_quad_spi_0_0_ooc.xdc

# XDC: d:/Entertaiment/Programy/VHDL/VHDL/Display/Display.srcs/sources_1/bd/design_1/ip/design_1_PmodMTDS_0_2/src/PmodMTDS_axi_quad_spi_0_0/PmodMTDS_axi_quad_spi_0_0_clocks.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==PmodMTDS_axi_quad_spi_0_0 || ORIG_REF_NAME==PmodMTDS_axi_quad_spi_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: d:/Entertaiment/Programy/VHDL/VHDL/Display/Display.srcs/sources_1/bd/design_1/ip/design_1_PmodMTDS_0_2/src/PmodMTDS_axi_gpio_0_0/PmodMTDS_axi_gpio_0_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==PmodMTDS_axi_gpio_0_0 || ORIG_REF_NAME==PmodMTDS_axi_gpio_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: d:/Entertaiment/Programy/VHDL/VHDL/Display/Display.srcs/sources_1/bd/design_1/ip/design_1_PmodMTDS_0_2/src/PmodMTDS_axi_gpio_0_0/PmodMTDS_axi_gpio_0_0_ooc.xdc

# XDC: d:/Entertaiment/Programy/VHDL/VHDL/Display/Display.srcs/sources_1/bd/design_1/ip/design_1_PmodMTDS_0_2/src/PmodMTDS_axi_gpio_0_0/PmodMTDS_axi_gpio_0_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==PmodMTDS_axi_gpio_0_0 || ORIG_REF_NAME==PmodMTDS_axi_gpio_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: d:/Entertaiment/Programy/VHDL/VHDL/Display/Display.srcs/sources_1/bd/design_1/ip/design_1_PmodMTDS_0_2/src/axi_timer_0/axi_timer_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==axi_timer_0 || ORIG_REF_NAME==axi_timer_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: d:/Entertaiment/Programy/VHDL/VHDL/Display/Display.srcs/sources_1/bd/design_1/ip/design_1_PmodMTDS_0_2/src/axi_timer_0/axi_timer_0_ooc.xdc

# IP: d:/Entertaiment/Programy/VHDL/VHDL/Display/Display.srcs/sources_1/bd/design_1/ip/design_1_PmodMTDS_0_2/design_1_PmodMTDS_0_2.xci
# IP: The module: 'design_1_PmodMTDS_0_2' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: d:/Entertaiment/Programy/VHDL/VHDL/Display/Display.srcs/sources_1/bd/design_1/ip/design_1_PmodMTDS_0_2/src/PmodMTDS_pmod_bridge_0_0/PmodMTDS_pmod_bridge_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==PmodMTDS_pmod_bridge_0_0 || ORIG_REF_NAME==PmodMTDS_pmod_bridge_0_0} -quiet] -quiet

# IP: d:/Entertaiment/Programy/VHDL/VHDL/Display/Display.srcs/sources_1/bd/design_1/ip/design_1_PmodMTDS_0_2/src/PmodMTDS_axi_quad_spi_0_0/PmodMTDS_axi_quad_spi_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==PmodMTDS_axi_quad_spi_0_0 || ORIG_REF_NAME==PmodMTDS_axi_quad_spi_0_0} -quiet] -quiet

# IP: d:/Entertaiment/Programy/VHDL/VHDL/Display/Display.srcs/sources_1/bd/design_1/ip/design_1_PmodMTDS_0_2/src/PmodMTDS_axi_gpio_0_0/PmodMTDS_axi_gpio_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==PmodMTDS_axi_gpio_0_0 || ORIG_REF_NAME==PmodMTDS_axi_gpio_0_0} -quiet] -quiet

# IP: d:/Entertaiment/Programy/VHDL/VHDL/Display/Display.srcs/sources_1/bd/design_1/ip/design_1_PmodMTDS_0_2/src/axi_timer_0/axi_timer_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==axi_timer_0 || ORIG_REF_NAME==axi_timer_0} -quiet] -quiet

# XDC: d:/Entertaiment/Programy/VHDL/VHDL/Display/Display.srcs/sources_1/bd/design_1/ip/design_1_PmodMTDS_0_2/src/PmodMTDS_pmod_bridge_0_0/PmodMTDS_pmod_bridge_0_0_board.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==PmodMTDS_pmod_bridge_0_0 || ORIG_REF_NAME==PmodMTDS_pmod_bridge_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: d:/Entertaiment/Programy/VHDL/VHDL/Display/Display.srcs/sources_1/bd/design_1/ip/design_1_PmodMTDS_0_2/src/PmodMTDS_pmod_bridge_0_0/src/pmod_concat_ooc.xdc

# XDC: d:/Entertaiment/Programy/VHDL/VHDL/Display/Display.srcs/sources_1/bd/design_1/ip/design_1_PmodMTDS_0_2/design_1_PmodMTDS_0_2_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_PmodMTDS_0_2'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: d:/Entertaiment/Programy/VHDL/VHDL/Display/Display.srcs/sources_1/bd/design_1/ip/design_1_PmodMTDS_0_2/src/PmodMTDS_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_PmodMTDS_0_2'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: d:/Entertaiment/Programy/VHDL/VHDL/Display/Display.srcs/sources_1/bd/design_1/ip/design_1_PmodMTDS_0_2/src/PmodMTDS_axi_quad_spi_0_0/PmodMTDS_axi_quad_spi_0_0_board.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==PmodMTDS_axi_quad_spi_0_0 || ORIG_REF_NAME==PmodMTDS_axi_quad_spi_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: d:/Entertaiment/Programy/VHDL/VHDL/Display/Display.srcs/sources_1/bd/design_1/ip/design_1_PmodMTDS_0_2/src/PmodMTDS_axi_quad_spi_0_0/PmodMTDS_axi_quad_spi_0_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==PmodMTDS_axi_quad_spi_0_0 || ORIG_REF_NAME==PmodMTDS_axi_quad_spi_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: d:/Entertaiment/Programy/VHDL/VHDL/Display/Display.srcs/sources_1/bd/design_1/ip/design_1_PmodMTDS_0_2/src/PmodMTDS_axi_quad_spi_0_0/PmodMTDS_axi_quad_spi_0_0_ooc.xdc

# XDC: d:/Entertaiment/Programy/VHDL/VHDL/Display/Display.srcs/sources_1/bd/design_1/ip/design_1_PmodMTDS_0_2/src/PmodMTDS_axi_quad_spi_0_0/PmodMTDS_axi_quad_spi_0_0_clocks.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==PmodMTDS_axi_quad_spi_0_0 || ORIG_REF_NAME==PmodMTDS_axi_quad_spi_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: d:/Entertaiment/Programy/VHDL/VHDL/Display/Display.srcs/sources_1/bd/design_1/ip/design_1_PmodMTDS_0_2/src/PmodMTDS_axi_gpio_0_0/PmodMTDS_axi_gpio_0_0_board.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==PmodMTDS_axi_gpio_0_0 || ORIG_REF_NAME==PmodMTDS_axi_gpio_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: d:/Entertaiment/Programy/VHDL/VHDL/Display/Display.srcs/sources_1/bd/design_1/ip/design_1_PmodMTDS_0_2/src/PmodMTDS_axi_gpio_0_0/PmodMTDS_axi_gpio_0_0_ooc.xdc

# XDC: d:/Entertaiment/Programy/VHDL/VHDL/Display/Display.srcs/sources_1/bd/design_1/ip/design_1_PmodMTDS_0_2/src/PmodMTDS_axi_gpio_0_0/PmodMTDS_axi_gpio_0_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==PmodMTDS_axi_gpio_0_0 || ORIG_REF_NAME==PmodMTDS_axi_gpio_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: d:/Entertaiment/Programy/VHDL/VHDL/Display/Display.srcs/sources_1/bd/design_1/ip/design_1_PmodMTDS_0_2/src/axi_timer_0/axi_timer_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==axi_timer_0 || ORIG_REF_NAME==axi_timer_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: d:/Entertaiment/Programy/VHDL/VHDL/Display/Display.srcs/sources_1/bd/design_1/ip/design_1_PmodMTDS_0_2/src/axi_timer_0/axi_timer_0_ooc.xdc
